# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  paycheckapi:
    image: paycheckapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - ASPNETCORE_URLS=https://+;http://+
